### ISSUE TITLE
Bugs with Translations of Admin UI

### ISSUE THREAD

**Issue by proddata** [crate/crate-admin#697]
**Bug while changing languages at CrateDB-Help-page**
When changing the language at the CrateDB-Help page only one part of the description changes. When changing to another menu and opening the help-menu again, the entire text shows up in the right language. Tested with changing between English, German and Spanish.
![image](https://user-images.githubusercontent.com/23557193/95828877-cdac9700-0d35-11eb-806d-ec99bbad190b.png)

**Fix typo on German CrateDB-Help-page**
Change marked sentence to: "Allerdings können in einer Produktionsumgebung bis zu **mehrere** tausend Datensätze pro Sekunde indiziert werden."
![image](https://user-images.githubusercontent.com/23557193/95828915-ddc47680-0d35-11eb-8534-2751b6d44691.png)

copy from Impediment board

**Comment by amotl** [comment]
Hi Georg,

thanks for reporting this.

> When changing the language at the CrateDB-Help page only one part of the description changes. When changing to another menu and opening the help-menu again, the entire text shows up in the right language.

I believe this has been fixed with one of my recent improvements to the translation subsystem.

Regarding your feedback about wording on the help page attaching to the Twitter import example, I believe they are obsolete because this example has been removed already.

With kind regards,
Andreas.
