### ISSUE TITLE
Bug: Jumping between selected views in view list

### ISSUE THREAD

**Issue by proddata** [crate/crate-admin#775]
There seems to be a bug in the view list / menu (tested with 5.0.0)

Sometimes when selecting a view, CrateDB jumps back to the first view in the list, instead of staying at the selected item.
I assume this is an issue with some deferred backend call.

**Steps to Reproduce**

1) Create at least 2 views

```sql
CREATE VIEW v1 AS SELECT 1;
CREATE VIEW v2 AS SELECT 1;
```
2) go to **view list** and select VIEW v2.

**Actual Result**
-> Admin UI is jumping back to VIEW v1

**Expected Result**
Should stay at VIEW v2

**Comment by amotl** [comment]
Dear Georg,

thanks for the report. Can I ask you to quickly check if the observed behavior may be similar to what we found and mitigated with #700 and #708?

Back then, the fix was d7b865ecbfa, and I never was completely sure if this was correct at all, because the code might have had some valid intentions beforehand.

With kind regards,
Andreas.
